<!-- STORIES SECTION... -->
    <section class="!p-4">
        <div class="container-3xl-w mx-auto">
            <!-- Stories / Reels Swiper -->
            <div class="stories-container">
                <div class="relative">
                    <div class="stories-scroll">
                        <div class="stories-list" id="storiesList">
                            <!-- Story rings will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



<!-- Story Viewer -->
<div class="story-viewer" id="storyViewer">
    <div class="story-viewer-content">
        <!-- Progress bars -->
        <div class="story-progress" id="storyProgress">
            <!-- Progress bars will be generated by JavaScript -->
        </div>

        <!-- Header -->
        <div class="story-header">
            <div class="story-user-info">
                <div class="story-user-avatar">
                    <img id="viewerUserAvatar" src="" alt="" />
                </div>
                <div>
                    <div class="story-username" id="viewerUsername"></div>
                    <div class="story-timestamp" id="viewerTimestamp"></div>
                </div>
            </div>
            <div class="story-controls">
                <button class="story-control-btn" id="muteBtn" style="display: none">
                    <svg class="icon" viewBox="0 0 24 24">
                        <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon>
                        <path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path>
                        <path d="M19.07 4.93a10 10 0 0 1 0 14.14"></path>
                    </svg>
                </button>
                <button class="story-control-btn" id="closeBtn">
                    <svg class="icon" viewBox="0 0 24 24">
                        <line x1="18" y1="6" x2="6" y2="18"></line>
                        <line x1="6" y1="6" x2="18" y2="18"></line>
                    </svg>
                </button>
            </div>
        </div>

        <!-- Content -->
        <div class="story-content" id="storyContent">
            <img class="story-media" id="storyMedia" src="" alt="" />
            <div class="story-tap-areas">
                <div class="story-tap-area" data-action="prev"></div>
                <div class="story-tap-area" data-action="next"></div>
            </div>
        </div>

        <!-- Navigation arrows -->
        <div class="story-nav">
            <button class="story-nav-btn story-nav-prev" id="prevBtn">
                <svg class="icon icon-lg" viewBox="0 0 24 24">
                    <polyline points="15,18 9,12 15,6"></polyline>
                </svg>
            </button>
            <button class="story-nav-btn story-nav-next" id="nextBtn">
                <svg class="icon icon-lg" viewBox="0 0 24 24">
                    <polyline points="9,18 15,12 9,6"></polyline>
                </svg>
            </button>
        </div>

        <!-- Pause indicator -->
        <div class="pause-indicator" id="pauseIndicator">
            <div class="pause-icon">
                <div class="pause-bar"></div>
                <div class="pause-bar"></div>
            </div>
        </div>
    </div>
</div>